FROM python:3.11-slim

WORKDIR /app

COPY app/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY app /app

ENV DB_PATH=/app/data/sensors.db
ENV SCHEMA_PATH=/app/schema.sql

RUN python /app/init_db.py

EXPOSE 5000

CMD ["python", "/app/app.py"]
